"""Add bounty_upgrades table for premium placement

Revision ID: 03ddca00060d
Revises: 23a99a51b430
Create Date: 2026-04-24 05:29:35.895292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ddca00060d'
down_revision = '23a99a51b430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounty_upgrades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bounty_id', sa.String(length=36), nullable=False),
    sa.Column('upgrade_type', sa.String(length=20), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stripe_payment_intent', sa.String(length=100), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bounty_upgrades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bounty_upgrades_bounty_id'), ['bounty_id'], unique=False)

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('bounty_upgrades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bounty_upgrades_bounty_id'))

    op.drop_table('bounty_upgrades')
    # ### end Alembic commands ###
