"""Remove referral offer fields

Revision ID: 23a99a51b430
Revises: 420bd5ffdf26
Create Date: 2026-04-24 04:42:47.333955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a99a51b430'
down_revision = '420bd5ffdf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('referral_subject')
        batch_op.drop_column('referral_details')
        batch_op.drop_column('referral_target')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_target', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referral_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referral_subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
