"""Rename candidate fields to referral fields

Revision ID: 420bd5ffdf26
Revises: de34acf69e20
Create Date: 2026-04-24 04:02:39.652584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420bd5ffdf26'
down_revision = 'de34acf69e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('referral_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('referral_target', sa.String(length=500), nullable=True))
        batch_op.drop_column('candidate_name')
        batch_op.drop_column('candidate_qualifications')
        batch_op.drop_column('target_companies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_companies', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('candidate_qualifications', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('candidate_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('referral_target')
        batch_op.drop_column('referral_details')
        batch_op.drop_column('referral_subject')

    # ### end Alembic commands ###
