"""Add LinkedIn-style profile fields

Revision ID: 75314a6263e5
Revises: ca46dad64411
Create Date: 2026-04-26 03:32:21.002908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75314a6263e5'
down_revision = 'ca46dad64411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('headline', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experiences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('open_to_work', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remote_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('availability_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('privacy_settings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_views')
        batch_op.drop_column('privacy_settings')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('salary_currency')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('availability_date')
        batch_op.drop_column('remote_preference')
        batch_op.drop_column('open_to_work')
        batch_op.drop_column('languages')
        batch_op.drop_column('certifications')
        batch_op.drop_column('portfolio')
        batch_op.drop_column('education')
        batch_op.drop_column('experiences')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('headline')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
