"""Check for any missing model changes

Revision ID: a0872675a8ca
Revises: 75314a6263e5
Create Date: 2026-05-04 01:19:00.641395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0872675a8ca'
down_revision = '75314a6263e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_level', sa.Integer(), nullable=True))
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_currency')
        batch_op.drop_column('availability_date')
        batch_op.drop_column('profile_views')
        batch_op.drop_column('languages')
        batch_op.drop_column('experiences')
        batch_op.drop_column('remote_preference')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('education')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('privacy_settings')
        batch_op.drop_column('github_url')
        batch_op.drop_column('open_to_work')
        batch_op.drop_column('portfolio')
        batch_op.drop_column('certifications')
        batch_op.drop_column('headline')
        batch_op.drop_column('salary_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('headline', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('portfolio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('open_to_work', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('privacy_settings', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remote_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experiences', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_views', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('availability_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salary_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('privacy_level')

    # ### end Alembic commands ###
