"""Add language field

Revision ID: c971ab3f5436
Revises: add_payer_type_and_agreements
Create Date: 2026-04-26 00:30:52.665194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c971ab3f5436'
down_revision = 'add_payer_type_and_agreements'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['third_party_payer_id'], ['id'])

    with op.batch_alter_table('bounty_payment_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bounty_payment_agreements_bounty_id'), ['bounty_id'], unique=False)
        batch_op.create_foreign_key(None, 'bounties', ['bounty_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['payer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['inviter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounty_payment_agreements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bounty_payment_agreements_bounty_id'))

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
