"""Add referral_offer direction and candidate fields

Revision ID: de34acf69e20
Revises: e78f404f8c48
Create Date: 2026-04-24 03:27:16.531605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de34acf69e20'
down_revision = 'e78f404f8c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('candidate_qualifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_companies', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('target_companies')
        batch_op.drop_column('candidate_qualifications')
        batch_op.drop_column('candidate_name')

    # ### end Alembic commands ###
