"""Add transaction_fee to bounties and matches

Revision ID: e78f404f8c48
Revises: fa6ff45fcb16
Create Date: 2026-04-24 00:41:13.829027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78f404f8c48'
down_revision = 'fa6ff45fcb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_fee', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_fee', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('transaction_fee')

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('transaction_fee')

    # ### end Alembic commands ###
